# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zhangs\Documents\Qt_Projects\Python\tcp_client\myui\MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 6, 0, 1, 4)
        self.recPB = QtWidgets.QPushButton(self.tab_3)
        self.recPB.setObjectName("recPB")
        self.gridLayout_3.addWidget(self.recPB, 14, 2, 1, 1)
        self.stopPB = QtWidgets.QPushButton(self.tab_3)
        self.stopPB.setObjectName("stopPB")
        self.gridLayout_3.addWidget(self.stopPB, 14, 3, 1, 1)
        self.timeLabel = QtWidgets.QLabel(self.tab_3)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout_3.addWidget(self.timeLabel, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 7, 0, 1, 1)
        self.getLocalPB = QtWidgets.QPushButton(self.tab_3)
        self.getLocalPB.setObjectName("getLocalPB")
        self.gridLayout_3.addWidget(self.getLocalPB, 0, 3, 1, 1)
        self.local_ip_LE = QtWidgets.QLineEdit(self.tab_3)
        self.local_ip_LE.setObjectName("local_ip_LE")
        self.gridLayout_3.addWidget(self.local_ip_LE, 0, 1, 1, 2)
        self.sendPB = QtWidgets.QPushButton(self.tab_3)
        self.sendPB.setObjectName("sendPB")
        self.gridLayout_3.addWidget(self.sendPB, 9, 3, 1, 1)
        self.hexCKB = QtWidgets.QCheckBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hexCKB.sizePolicy().hasHeightForWidth())
        self.hexCKB.setSizePolicy(sizePolicy)
        self.hexCKB.setObjectName("hexCKB")
        self.gridLayout_3.addWidget(self.hexCKB, 10, 3, 1, 1)
        self.connectPB = QtWidgets.QPushButton(self.tab_3)
        self.connectPB.setObjectName("connectPB")
        self.gridLayout_3.addWidget(self.connectPB, 5, 2, 1, 1)
        self.des_ip_LE = QtWidgets.QLineEdit(self.tab_3)
        self.des_ip_LE.setObjectName("des_ip_LE")
        self.gridLayout_3.addWidget(self.des_ip_LE, 3, 1, 1, 3)
        self.trigModCB = QtWidgets.QComboBox(self.tab_3)
        self.trigModCB.setObjectName("trigModCB")
        self.trigModCB.addItem("")
        self.trigModCB.addItem("")
        self.trigModCB.addItem("")
        self.gridLayout_3.addWidget(self.trigModCB, 7, 1, 1, 3)
        self.portLE = QtWidgets.QLineEdit(self.tab_3)
        self.portLE.setObjectName("portLE")
        self.gridLayout_3.addWidget(self.portLE, 4, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.timeModCB = QtWidgets.QComboBox(self.tab_3)
        self.timeModCB.setObjectName("timeModCB")
        self.timeModCB.addItem("")
        self.timeModCB.addItem("")
        self.gridLayout_3.addWidget(self.timeModCB, 8, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.timeLE = QtWidgets.QLineEdit(self.tab_3)
        self.timeLE.setObjectName("timeLE")
        self.gridLayout_3.addWidget(self.timeLE, 8, 1, 1, 2)
        self.discPB = QtWidgets.QPushButton(self.tab_3)
        self.discPB.setObjectName("discPB")
        self.gridLayout_3.addWidget(self.discPB, 5, 3, 1, 1)
        self.stateLed = LedIndicator(self.tab_3)
        self.stateLed.setText("")
        self.stateLed.setObjectName("stateLed")
        self.gridLayout_3.addWidget(self.stateLed, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.sendTE = QtWidgets.QPlainTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendTE.sizePolicy().hasHeightForWidth())
        self.sendTE.setSizePolicy(sizePolicy)
        self.sendTE.setObjectName("sendTE")
        self.gridLayout_3.addWidget(self.sendTE, 9, 0, 2, 3)
        self.gridLayout_3.setColumnStretch(1, 2)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setColumnStretch(3, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.msgTB = QtWidgets.QTextBrowser(self.groupBox_2)
        self.msgTB.setObjectName("msgTB")
        self.gridLayout_2.addWidget(self.msgTB, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.plotView = PlotWidget(self.centralwidget)
        self.plotView.setObjectName("plotView")
        self.gridLayout.addWidget(self.plotView, 0, 0, 2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInput = QtWidgets.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.menuFile.addAction(self.actionInput)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "参数选择"))
        self.recPB.setText(_translate("MainWindow", "接收数据"))
        self.stopPB.setText(_translate("MainWindow", "停止接收"))
        self.timeLabel.setText(_translate("MainWindow", "时间常数"))
        self.label_4.setText(_translate("MainWindow", "触发模式"))
        self.getLocalPB.setText(_translate("MainWindow", "获取本机IP"))
        self.sendPB.setText(_translate("MainWindow", "发送数据"))
        self.hexCKB.setText(_translate("MainWindow", "hex模式"))
        self.connectPB.setText(_translate("MainWindow", "连接网络"))
        self.des_ip_LE.setText(_translate("MainWindow", "127.0.0.1"))
        self.trigModCB.setItemText(0, _translate("MainWindow", "内触发"))
        self.trigModCB.setItemText(1, _translate("MainWindow", "外触发"))
        self.trigModCB.setItemText(2, _translate("MainWindow", "助手模式"))
        self.portLE.setText(_translate("MainWindow", "8951"))
        self.label_2.setText(_translate("MainWindow", "目标IP"))
        self.timeModCB.setItemText(0, _translate("MainWindow", "低模式"))
        self.timeModCB.setItemText(1, _translate("MainWindow", "高模式"))
        self.label.setText(_translate("MainWindow", "本机IP"))
        self.timeLE.setPlaceholderText(_translate("MainWindow", "时间单位 us"))
        self.discPB.setText(_translate("MainWindow", "断开网络"))
        self.label_3.setText(_translate("MainWindow", "端口号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "通信配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "状态信息"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.actionInput.setText(_translate("MainWindow", "输入"))
from LedIndicatorWidget import LedIndicator
from pyqtgraph import PlotWidget
